name: CI/CD Pipeline

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Pull from GitHub on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@52.4.229.207 << EOF
            cd /home/ubuntu/WH/TDT
            git checkout develop
            git pull origin develop
          EOF

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: List files for debugging
        run: ls -al

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        run: |
          docker build -t myapp .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        env:
          SQL_USER: ${{ secrets.SQL_USER }}
          SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
          PRIVATE_KEY_PATH: /secrets/private_key.pem
          PUBLIC_KEY_PATH: /secrets/public_key.pem
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          TAP_PARTNER_KEY: ${{ secrets.TAP_PARTNER_KEY }}
          MERCHANT_ID: ${{ secrets.MERCHANT_ID }}
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@52.4.229.207 << EOF
            cd /home/ubuntu/WH/TDT
            docker compose down
            docker compose up --build -d
          EOF
