name: CI/CD Pipeline

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        run: |
          docker build -t myapp .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        env:
          SQL_USER: ${{ secrets.SQL_USER }}
          SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
          PRIVATE_KEY_PATH: ${{ secrets.PRIVATE_KEY_PATH }}
          PUBLIC_KEY_PATH: ${{ secrets.PUBLIC_KEY_PATH }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          TAP_PARTNER_KEY: ${{ secrets.TAP_PARTNER_KEY }}
          MERCHANT_ID: ${{ secrets.MERCHANT_ID }}
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@52.4.229.207 << EOF
            export SQL_USER=${{ secrets.SQL_USER }}
            export SQL_PASSWORD=${{ secrets.SQL_PASSWORD }}
            export PRIVATE_KEY_PATH=${{ secrets.PRIVATE_KEY_PATH }}
            export PUBLIC_KEY_PATH=${{ secrets.PUBLIC_KEY_PATH }}
            export REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
            export TAP_PARTNER_KEY=${{ secrets.TAP_PARTNER_KEY }}
            export MERCHANT_ID=${{ secrets.MERCHANT_ID }}
            cd /home/ubuntu/WH/TDT
            git pull origin develop
            docker compose down
            docker compose up --build -d
          EOF
