name: CI/CD Pipeline

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Pull from GitHub on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@52.4.229.207 << EOF
            cd /home/ubuntu/WH/TDT
            git checkout develop
            git pull origin develop
          EOF

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        run: |
          docker build -t myapp .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        env:
          SQL_USER: ${{ secrets.SQL_USER }}
          SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
          PRIVATE_KEY_PATH: /app/secrets/private_key.pem
          PUBLIC_KEY_PATH: /app/secrets/public_key.pem
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          TAP_PARTNER_KEY: ${{ secrets.TAP_PARTNER_KEY }}
          MERCHANT_ID: ${{ secrets.MERCHANT_ID }}

          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_SESSION_SECRET_KEY: ${{ secrets.GOOGLE_SESSION_SECRET_KEY }}

          PERSONAL_GMAIL: ${{ secrets.PERSONAL_GMAIL }}
          PERSONAL_GMAIL_PASSWORD: ${{ secrets.PERSONAL_GMAIL_PASSWORD }}

        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@52.4.229.207 << EOF
            cd /home/ubuntu/WH/TDT

            export SQL_USER=${SQL_USER}
            export SQL_PASSWORD=${SQL_PASSWORD}
            export REDIS_PASSWORD=${REDIS_PASSWORD}
            export TAP_PARTNER_KEY=${TAP_PARTNER_KEY}
            export MERCHANT_ID=${MERCHANT_ID}
            export GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
            export GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
            export GOOGLE_SESSION_SECRET_KEY=${GOOGLE_SESSION_SECRET_KEY}

            export PERSONAL_GMAIL=${PERSONAL_GMAIL}
            export PERSONAL_GMAIL_PASSWORD=${PERSONAL_GMAIL_PASSWORD}

            docker compose down
            docker compose up --build -d
          EOF
